### ISSUE TITLE
Implement proper DAQ Dummy

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MPIMeasurements.jl#19]
This issue is for the DAQ dummy. 

- [ ] Rename it. The RedPitaya should not be in the name
- [ ] Implement a rough version that is not fully functional
- [ ] Implement a simulation of the DF pipeline, i.e. make a connection between the set tx values and the ref channels
- [ ] Implement a simple SPIO simulation. This will likely involve MPISimulation and is a long term goal.

The first two points are rather important since they allow us to do unit testing of all the high-level infrastructure.

**Comment by jonschumacher** [comment]
Ideally, this would be stateful in a sense that we have a temperature rise (retrievable by dummy temperature sensors) resulting in a drift of amplitude and phase for testing the control loop.
