### ISSUE TITLE
Lower dimension robots

### ISSUE THREAD

**Issue by jusack** [MagneticParticleImaging/MPIMeasurements.jl#24]
Hi,

while looking at the interface for robots defined in [Robots.jl](https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/master/src/Robots/Robots.jl#L10) I noticed, that in all functions a three dimensional robot is assumed. I am trying to implement an 1D moving table, so I am thinking about ways this could be integrated into the existing interface. 

Is there a reason, that the interface requires three individual values for moveAbs while the general functions accepts vectors and hands the individual values to the device?

If this is open for changes the interface could be adjusted so that all device specific movement commands are internal functions of the form
```julia
@mustimplement _moveAbs(robot::Robot, pos::Vector{typeof(1.0Unitful.mm)})`
```
with a range of general movement functions with range and argument checking being defined on the base type.

This would also clarify another thing: Right now `moveAbsUnsafe(rob::IselRobot, [1.0Unitful.mm, 1.0Unitful.mm, 1.0Unitful.mm])` and `moveAbs(rob::IselRobot, 1.0Unitful.mm, 1.0Unitful.mm, 1.0Unitful.mm)` result in the same "unsafe" behaviour, which would be clarified by marking the robot specific `moveAbs` as an internal function.

To allow different robot configurations a function like
```julia
@mustimplement degreesOfFreedom(robot::Robot)
```
could be used.

In my opinion this could make the interface for the robots more general. However I am not sure how the Robot interface is used in your group, so I wanted to share my thoughts before changing the interface and opening a pull request.

Another point that I was thinking about is, if it would be beneficial to use `Unitful.Length` instead of `typeof(1.0Unitful.mm)`, which would allow also other units (m, cm) and other datatypes like integers. The conversion into the correct unit and datatype can then be done in the lowest level function of each robot (i.e `mm2steps` or `createMoveCommand`) with `ustrip(Float64, Unitful.mm, x)` or similar.

**Comment by tknopp** [comment]
I am open to changes and a more general interface. Important is just that we enable/implement tests before we change anything and that we use semantic versioning such that I can port to new APIs.

Making the positions arbitrary dimensioned fits good to our "position" API that you can find here: https://github.com/MagneticParticleImaging/MPIFiles.jl/blob/master/src/positions/Positions.jl

Regarding `Unitful` we probably should discuss how and if we want to use it. Honestly in most other places I removed it altogether since it makes writing generic code complicated. It always gets complicated if you need, for instance, write positions to toml files or hdf5 files.

**Comment by hofmannmartin** [comment]
> Another point that I was thinking about is, if it would be beneficial to use Unitful.Length instead of typeof(1.0Unitful.mm), which would allow also other units (m, cm) and other datatypes like integers. The conversion into the correct unit and datatype can then be done in the lowest level function of each robot (i.e mm2steps or createMoveCommand) with ustrip(Float64, Unitful.mm, x) or similar.

Maybe we could be even more general and allow the specification of angles in case we have a robot with a rotation axis?

> Regarding Unitful we probably should discuss how and if we want to use it. Honestly in most other places I removed it altogether since it makes writing generic code complicated. It always gets complicated if you need, for instance, write positions to toml files or hdf5 files.

I agree that the units have their downsides. On the other hand they provide a lot of information, serve as documentation and act as an additional barrier to user errors.
