### ISSUE TITLE
Storage of Feedback Channels and Temperature

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MPIMeasurements.jl#48]
We currently do not store the information from the feedback channels but this is very valuable information. In fact, Bruker does store these in their `rawdata.job1/2` files. What needs to be store is the Γ and Ω matrices. Either we do it per period or per frame, that is not entirely clear for me. Per period is even better but we need to look at the storage cost.

Independently of that we want to store additional signals that are not coming from the DAQ. Right now temperatures are the most urgent one but we may also want to store other signals. Here we need to think if we want to synchronize these signals with the frames or not. Currently we have some infrastructure to store temperatures independently where we use timestamps. This is extremely flexible. But if we want to store this for system matrices, it would be more handy to have it synchronized.

**Comment by nHackel** [comment]
All SerialPort-Devices are now multi-threading safe, so we can also monitor them in the GUI (and even safe them here) while also accessing the TempSensor in a protocol execution, probably in the respective asyncConsumer calls

**Comment by nHackel** [comment]
This is now implemented with the control code update and the new ChainableBuffer infrastructure and can also be extended to other sensor data
