### ISSUE TITLE
Move all concrete devices to separate repositories/packages

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIMeasurements.jl#59]
@nHackel @tknopp The loading times of MPIMeasurements are growing steadily. How do you think about splitting off all the concrete devices into separate packages? The could live within this repository but should not be loaded by default. This should reduce loading times quite a bit. Additionally it splits testing in smaller chunks and we could try to actually get `MPIMeasurements` covered with tests,

This would probably result in the following sub-packages
- `MPIMeasurementsRedPitaya`
- `MPIMeasurementsTinkerforge`
- `MPIMeasurementsIsel`
- `MPIMeasurementsIgus`
- `MPIMeasurementsLakeshore`
- `MPIMeasurementsStepcraft`
- `MPIMeasurementsFOTemperature`
- `MPIMeasurementsArduinoTemperature`
- `MPIMeasurementsArduinoSurveillance`
- `MPIMeasurementsArduinoHallsensor`

The only device that should diectly be loaded with `using` should probably be `MPIMeasurementsRedPitaya`. All other devices would then require something like

```
using MPIMeasurements<PackageSuffix>
using MPIMeasurements
```

Do you think that is a feasible approach? Of course it would make the usage of specific devices a bit more to type but this can easily be mitigated by just putting everything into a script or even into the `startup.jl`. I do not see a way to dynamically load the device packages depending on the devices specified in the `Scanner.toml`.

PS: The mechanics of splitting have been discussed in https://discourse.julialang.org/t/usage-of-subdirectories-to-store-multiple-packages-in-a-single-repo/55534

**Comment by tknopp** [comment]
The question is, whether the device code is really effecting the load time or if it is rather the amount of dependencies. Having one package per device sounds like a very high administrative overhead.

In general, I am in favor of more fine-grained modularization though. We recently did something similar in [MRIReco](https://github.com/MagneticResonanceImaging/MRIReco.jl), which worked out quite well. But I am not sure if that should be done along devices.

I have seen that you were picking low-hanging fruits in https://github.com/MagneticParticleImaging/MPIMeasurements.jl/pull/60
Could you comment on the impact of that?

And by the way, have you seen `@time_imports`. It helped me finding the big load time dependencies. I used it in combination with https://github.com/peng1999/PkgDependency.jl, since I was not sure where certain indirect dependencies came from.

**Comment by jonschumacher** [comment]
Thanks for the hint to `@time_imports` and `PkgDependeny`. I noticed that there is also `PkgGraph.LoadTime.time_imports("PyPlot");` but I did not yet manage to generate a graph image out of it. I tracked down some portion of the loading time to some packages introduced in `RedPitayaDAQServer` for updating the RP remotely. I removed them for now. They might be a better fit for a script anyways. Another portion can be attributed to the Tinkerforge devices and PyCall which seems to recompile a lot of code every time it is loaded. The main loading time stems from `MPIFiles` so making it faster would give a huge benefit. I guess, I will just move the Tinkerforge devices to a separate package and if need arises we can move other device types to separate packages as well.

Concerning your question on #60:

I ran the following code on both `master` and my branch:
```
using PkgGraph
using Statistics
N = 5;
times = []
for i=1:N
   total_time = 0
   for tuple_ in PkgGraph.LoadTime.time_imports("MPIMeasurements")
     total_time += tuple_[:time_ms]
   end
   push!(times, total_time)
end
@info "" mean(times) std(times)
```
For my branch it reported 22175±4655 ms and for `master` 20383±2647 ms. This is a bit strange since I only removed dependencies. I would happily attribute this to background processes on my computer but running the code multiple times for each case confirmed the trend. I will merge #60 anyways since it makes sense to remove stale dependencies and split off the Tinkerforge devices and then dig further.

**Comment by jonschumacher** [comment]
With the move of the Tinkerforge devices in #60 I am now down to 16168±3574 ms. That is not the optimum but we might get there gradually. The other devices are not so heavy in terms of dependencies, but now we have an example on how to factor out devices. I will merge #60 now which will close this issue and if need arises we can factor out more devices.
